[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[git_branch]
symbol = "ï…— "

[conda]
symbol = "ğŸ‰ "
ignore_base = false

# https://github.com/starship/starship/issues/5350
[battery]
disabled = true

[python]
python_binary = "_starship_python.sh"

[gcloud]
detect_env_vars = ['CLOUDSDK_CONFIG']

[env_var.CUDA_HOME]
