[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[git_branch]
symbol = "ï…— "

[conda]
symbol = "ğŸ‰ "
ignore_base = false

# https://github.com/starship/starship/issues/5350
[battery]
disabled = true
