[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"

[git_branch]
symbol = "ï…— "

[conda]
symbol = "ğŸ‰ "
ignore_base = false

[python]
python_binary = [["uv", "run", "--no-python-downloads", "python"]]

[gcloud]
detect_env_vars = ['CLOUDSDK_CONFIG']

[env_var.CUDA_HOME]
